import type { Idea, Text, Category, Brainstorm } from '@/types'

export const MOCK_CATEGORIES: Category[] = [
  { id: 'cat-1', user_id: 'demo', name: 'Desenvolvimento do Amazonas', color: '#F59E0B', created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
  { id: 'cat-2', user_id: 'demo', name: 'Regularização Fundiária', color: '#10B981', created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
  { id: 'cat-3', user_id: 'demo', name: 'BR-319', color: '#3B82F6', created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
  { id: 'cat-4', user_id: 'demo', name: 'BR-174', color: '#8B5CF6', created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
  { id: 'cat-5', user_id: 'demo', name: 'Interior do Amazonas', color: '#EF4444', created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
  { id: 'cat-6', user_id: 'demo', name: 'Turismo', color: '#06B6D4', created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
  { id: 'cat-7', user_id: 'demo', name: 'Saúde', color: '#EC4899', created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
  { id: 'cat-8', user_id: 'demo', name: 'Educação', color: '#F97316', created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
  { id: 'cat-9', user_id: 'demo', name: 'Infraestrutura', color: '#6B7280', created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
  { id: 'cat-10', user_id: 'demo', name: 'Mandato', color: '#14B8A6', created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
  { id: 'cat-11', user_id: 'demo', name: 'Pré-campanha', color: '#EAB308', created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
  { id: 'cat-12', user_id: 'demo', name: 'Datas Comemorativas', color: '#A855F7', created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
  { id: 'cat-13', user_id: 'demo', name: 'Respostas Políticas', color: '#F43F5E', created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
  { id: 'cat-14', user_id: 'demo', name: 'Discursos', color: '#84CC16', created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
  { id: 'cat-15', user_id: 'demo', name: 'Releases', color: '#0EA5E9', created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
  { id: 'cat-16', user_id: 'demo', name: 'Ideias Brutas', color: '#78716C', created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
]

export const MOCK_IDEAS: Idea[] = [
  {
    id: 'idea-1',
    user_id: 'demo',
    title: 'Desenvolvimento do Amazonas como prioridade nacional',
    description: 'O Amazonas representa 18% do território brasileiro mas recebe menos de 3% dos investimentos federais. Precisamos mostrar essa injustiça com dados concretos e propor um plano de equalização regional.',
    category_id: 'cat-1',
    category: MOCK_CATEGORIES[0],
    urgency: 'alta',
    status: 'em_desenvolvimento',
    tags: [{ id: 't1', user_id: 'demo', name: 'Amazonas', created_at: '2026-01-01T00:00:00Z' }, { id: 't2', user_id: 'demo', name: 'Desenvolvimento', created_at: '2026-01-01T00:00:00Z' }],
    created_at: '2026-04-15T10:00:00Z',
    updated_at: '2026-04-20T14:30:00Z',
  },
  {
    id: 'idea-2',
    user_id: 'demo',
    title: 'Regularização fundiária no interior: quem tem terra, tem futuro',
    description: 'Milhares de famílias ribeirinhas e caboclas vivem sem título de propriedade há gerações. A regularização fundiária é o caminho para acessar crédito, financiamento e permanecer no campo com dignidade.',
    category_id: 'cat-2',
    category: MOCK_CATEGORIES[1],
    urgency: 'alta',
    status: 'transformada',
    tags: [{ id: 't3', user_id: 'demo', name: 'Interior', created_at: '2026-01-01T00:00:00Z' }, { id: 't4', user_id: 'demo', name: 'Caboclo', created_at: '2026-01-01T00:00:00Z' }],
    created_at: '2026-04-10T09:00:00Z',
    updated_at: '2026-04-18T11:00:00Z',
  },
  {
    id: 'idea-3',
    user_id: 'demo',
    title: 'BR-319: a rodovia que conecta o Amazonas ao Brasil',
    description: 'A recuperação da BR-319 não é só uma obra de asfalto. É a integração do Amazonas com o restante do país, o escoamento da produção do interior e o acesso a serviços básicos para quem vive isolado.',
    category_id: 'cat-3',
    category: MOCK_CATEGORIES[2],
    urgency: 'alta',
    status: 'em_desenvolvimento',
    tags: [{ id: 't5', user_id: 'demo', name: 'Infraestrutura', created_at: '2026-01-01T00:00:00Z' }, { id: 't6', user_id: 'demo', name: 'Interior', created_at: '2026-01-01T00:00:00Z' }],
    created_at: '2026-04-05T08:00:00Z',
    updated_at: '2026-04-16T16:00:00Z',
  },
  {
    id: 'idea-4',
    user_id: 'demo',
    title: 'Presidente Figueiredo — Terra das Cachoeiras: turismo como desenvolvimento',
    description: 'Presidente Figueiredo tem potencial turístico imenso e ainda pouco explorado. Com estrutura e divulgação certa, pode se tornar referência no Amazonas e gerar emprego e renda para a população local.',
    category_id: 'cat-6',
    category: MOCK_CATEGORIES[5],
    urgency: 'media',
    status: 'bruta',
    tags: [{ id: 't7', user_id: 'demo', name: 'Presidente Figueiredo', created_at: '2026-01-01T00:00:00Z' }, { id: 't8', user_id: 'demo', name: 'Terra das Cachoeiras', created_at: '2026-01-01T00:00:00Z' }],
    created_at: '2026-04-22T14:00:00Z',
    updated_at: '2026-04-22T14:00:00Z',
  },
  {
    id: 'idea-5',
    user_id: 'demo',
    title: 'Interior do Amazonas: o coração esquecido do estado',
    description: 'Os municípios do interior do Amazonas, acessíveis apenas por rio ou avião, vivem em condição de abandono histórico. Um discurso potente que mostre essa realidade com emoção e dados.',
    category_id: 'cat-5',
    category: MOCK_CATEGORIES[4],
    urgency: 'media',
    status: 'em_desenvolvimento',
    tags: [{ id: 't9', user_id: 'demo', name: 'Sustentabilidade', created_at: '2026-01-01T00:00:00Z' }, { id: 't10', user_id: 'demo', name: 'Emprego e renda', created_at: '2026-01-01T00:00:00Z' }],
    created_at: '2026-04-28T11:00:00Z',
    updated_at: '2026-04-30T09:00:00Z',
  },
]

export const MOCK_TEXTS: Text[] = [
  {
    id: 'text-1',
    user_id: 'demo',
    idea_id: 'idea-1',
    title: 'Amazônia não é periferia do Brasil — roteiro 60s',
    content: `O Amazonas ocupa quase um quinto do Brasil. Nossa floresta protege o clima do planeta. Nossas águas abastecem o continente. Nosso povo trabalha, sonha e contribui para essa nação.\n\nMas quando chegamos à mesa das decisões, somos tratados como periferia. Menos hospitais, menos estradas, menos investimento.\n\nIsso precisa mudar. O Amazonas não pede favor — pede justiça. Pede a sua parte naquilo que o Brasil constrói com a riqueza que vem da nossa terra.\n\nA Amazônia não é periferia do Brasil. A Amazônia É o Brasil.`,
    category_id: 'cat-1',
    category: MOCK_CATEGORIES[0],
    status: 'pronto',
    format: 'video',
    word_count: 89,
    scheduled_date: '2026-05-15',
    notes: 'Gravar em frente ao rio ou na Ponta Negra. Tom firme mas esperançoso.',
    tags: [{ id: 't1', user_id: 'demo', name: 'Amazonas', created_at: '2026-01-01T00:00:00Z' }],
    created_at: '2026-04-20T15:00:00Z',
    updated_at: '2026-04-25T10:00:00Z',
  },
  {
    id: 'text-2',
    user_id: 'demo',
    idea_id: 'idea-2',
    title: 'Legenda — Regularização Fundiária no Amazonas',
    content: `🌿 Quem tem terra, tem futuro.\n\nNos rios e matas do Amazonas, há famílias que vivem na mesma terra há 3 gerações — mas nunca tiveram um papel que diga que aquela terra é delas.\n\nSem título, não tem crédito. Sem crédito, não tem investimento. Sem investimento, não tem futuro.\n\nA regularização fundiária não é burocracia — é dignidade.\n\n📍 Das várzeas do rio ao coração da floresta, vamos garantir que quem produz, quem planta e quem cuida da terra tenha o direito reconhecido.\n\n#Amazonas #RegularizaçãoFundiária #Interior #Floresta #AgriculturaFamiliar #DesenvolvimentoRegional`,
    category_id: 'cat-2',
    category: MOCK_CATEGORIES[1],
    status: 'gravado',
    format: 'legenda',
    word_count: 115,
    tags: [{ id: 't3', user_id: 'demo', name: 'Interior', created_at: '2026-01-01T00:00:00Z' }],
    created_at: '2026-04-18T12:00:00Z',
    updated_at: '2026-04-22T09:00:00Z',
  },
  {
    id: 'text-3',
    user_id: 'demo',
    idea_id: 'idea-3',
    title: 'Discurso — BR-319: a estrada da integração',
    content: `Presidente, senhoras e senhores.\n\nQuando falamos da BR-319, não falamos apenas de quilômetros de asfalto. Falamos de gente. De famílias que levam horas de barco para chegar ao hospital mais próximo. De agricultores que perdem a colheita porque não há como escoar a produção. De crianças que não chegam à escola nos dias de chuva.\n\nA BR-319 recuperada é mais do que uma estrada — é a conexão de meio milhão de brasileiros com o restante do país.\n\nO Amazonas não pode continuar sendo o único estado cuja capital só é acessível por avião ou barco. Isso não é vocação geográfica. Isso é abandono histórico.\n\nHoje, defendemos a recuperação da BR-319 com responsabilidade socioambiental, com diálogo com as comunidades e com planejamento de longo prazo. Porque desenvolvimento real é aquele que inclui todos — inclusive quem mora às margens dos nossos rios e florestas.\n\nObrigado.`,
    category_id: 'cat-3',
    category: MOCK_CATEGORIES[2],
    status: 'rascunho',
    format: 'discurso',
    word_count: 180,
    tags: [{ id: 't5', user_id: 'demo', name: 'Infraestrutura', created_at: '2026-01-01T00:00:00Z' }],
    created_at: '2026-04-16T17:00:00Z',
    updated_at: '2026-04-20T14:00:00Z',
  },
]

export const MOCK_BRAINSTORMS: Brainstorm[] = [
  {
    id: 'bs-1',
    user_id: 'demo',
    idea_id: 'idea-1',
    central_idea: 'O Amazonas contribui imensamente para o Brasil mas recebe investimento desproporcional à sua importância',
    problem_solved: 'Invisibilidade do Amazonas nas decisões nacionais e falta de investimento proporcional',
    target_audience: 'População amazonense, eleitores do interior, lideranças políticas',
    emotion: 'Orgulho regional + indignação justa + esperança de mudança',
    impact_phrase: 'O Amazonas não pede favor — pede justiça',
    main_arguments: 'Dados de investimento per capita; área territorial; contribuição ambiental; população vulnerável',
    local_examples: 'Municípios sem hospital, sem estrada pavimentada; custo do frete; isolamento na cheia',
    tone: 'firme',
    format: 'video',
    free_notes: 'Usar dados do IBGE e relatórios de investimento federal por estado',
    created_at: '2026-04-18T10:00:00Z',
    updated_at: '2026-04-18T10:00:00Z',
  },
]
